server:
    port: 8080

spring:
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/store
        username: postgres
        password: pass
    h2:
        console:
            enabled: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show-sql: true


